---
- name: Safely deploy compare-app on Kubernetes with readiness check and rollback
  hosts: localhost
  gather_facts: false
  vars:
    namespace: default
    deployment_name: compare-app
    image_repo: basmaoueslati/compare-appf25
    image_full: "{{ image_repo }}:{{ NEXT_VERSION }}"
    rollout_retries: 10
    rollout_delay: 15

  tasks:

    - name: Get current deployment info
      community.kubernetes.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ deployment_name }}"
      register: current_deployment
      ignore_errors: yes

    - name: Backup current deployment (if exists)
      copy:
        content: "{{ current_deployment.resources[0] | to_nice_yaml }}"
        dest: "/tmp/{{ deployment_name }}-backup.yaml"
      when: current_deployment.resources | length > 0

    - name: Patch deployment with new image or create if not exists
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ namespace }}"
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: "{{ deployment_name }}"
            template:
              metadata:
                labels:
                  app: "{{ deployment_name }}"
              spec:
                containers:
                  - name: "{{ deployment_name }}"
                    image: "{{ image_full }}"
      register: deployment_result

    - name: Wait for rollout to complete
      community.kubernetes.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ deployment_name }}"
      register: rollout_info
      retries: "{{ rollout_retries }}"
      delay: "{{ rollout_delay }}"
      until: rollout_info.resources and
             rollout_info.resources[0].status.readyReplicas is defined and
             rollout_info.resources[0].status.readyReplicas == rollout_info.resources[0].spec.replicas

    - name: Deployment successful
      debug:
        msg: "Deployment {{ deployment_name }} successfully rolled out with image {{ image_full }}"

