---
- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  vars:
    image_tag: "{{ NEXT_VERSION }}" 
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Build and Push Docker image
      community.docker.docker_image:
        name: "basmaoueslati/compare-appf25"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ build_context }}"
        push: yes
        state: present

    - name: Verify image was pushed
      command: docker pull basmaoueslati/compare-appf25:{{ image_tag }}
