---
- name: Safely deploy compare-app on Kubernetes with readiness check and rollback
  hosts: localhost
  gather_facts: yes
  vars:
    namespace: default
    app_name: compare-app
    container_name: compare-app
    new_image: "basmaoueslati/compare-app:{{ NEXT_VERSION }}"
    deployment_name: "{{ app_name }}"

  tasks:

    - name: Get current deployment info
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ deployment_name }}"
      register: current_deployment
      failed_when: false

    - name: Backup current deployment (if exists)
      set_fact:
        previous_deployment_spec: "{{ current_deployment.resources[0].spec if current_deployment.resources | length > 0 else {} }}"

    - name: Patch deployment with new image
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ namespace }}"
          spec:
            template:
              metadata:
                labels:
                  version: "{{ NEXT_VERSION }}"
              spec:
                containers:
                  - name: "{{ container_name }}"
                    image: "{{ new_image }}"

    - name: Wait for rollout to complete
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - "app={{ app_name }}"
          - "version={{ NEXT_VERSION }}"
      register: new_pods
      retries: 10
      delay: 10
      until: >
        new_pods.resources | selectattr('status.containerStatuses[0].ready', 'defined') |
        selectattr('status.containerStatuses[0].ready') | length > 0

    - name: Fail play if deployment is not ready
      fail:
        msg: "New deployment failed readiness check."
      when: >
        new_pods.resources | selectattr('status.containerStatuses[0].ready', 'defined') |
        selectattr('status.containerStatuses[0].ready') | length == 0

    - name: Print success message
      debug:
        msg: "Deployment updated successfully to {{ new_image }}"

